language: c
compiler:
        - gcc
env:
        - CFLAGS="-std=c99"
        - CFLAGS="-std=c89 -pedantic-errors"
os:
        - linux
        - osx
script:
        make ci && make test && make hardtest
